[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/pdfs/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
