[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/pdfs/*"
  [headers.values]
    Content-Disposition = "inline"
